"""updated models

Revision ID: ef9babe18c35
Revises: 9f542821a029
Create Date: 2025-11-25 11:14:51.290802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9babe18c35'
down_revision = '9f542821a029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=150), nullable=False))
        batch_op.drop_constraint(batch_op.f('url_record_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('url_record_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
